### ISSUE TITLE
Wiring

### ISSUE THREAD

**Issue by nhekkens** [igorkulman/rpi-thermometer#1]
Hey i was wondering if you could explain the sire wiring? 

Cheers

**Comment by igorkulman** [comment]
I am no HW expert, I used a tutorial with this scheme

![image](https://user-images.githubusercontent.com/4746070/67947361-c7d0ab00-fbe3-11e9-9a1b-b7c245a014be.png)

**Comment by igorkulman** [comment]
If you search for DS18B20 you will find multiple tutorial with various degrees of explanation.

**Comment by nhekkens** [comment]
Aamzing! thanks man
